stages:
  - test_ssh

test_ssh:
  stage: test_ssh
  image: docker.io/acampove/rx_run3:v2
  variables:
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p 7999 gitlab.cern.ch >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -i ~/.ssh/id_rsa -p 7999 -v git@gitlab.cern.ch || true
