image: docker.io/acampove/rx_run3:v2
# -----------
default:
  tags:
    - cvmfs
  id_tokens:
    LBAP_CI_JOB_JWT:  # generates a JSON Web Token (JWT) and assigns it to the env var $LBAP_CI_JOB_JWT
      aud: https://lbap.app.cern.ch
before_script:
    - git config --global color.ui always # Enable colored output for git
# -----------
stages :
  - build
  - test
# -----------
ssh:
  stage: build 
  script:
    - mkdir -p .ssh
    - echo "$SSH_USER_KEY" | tr -d '\r' > .ssh/id_rsa_user
    - chmod 600 .ssh/id_rsa_user
    - echo $PWD/.ssh
    - ls $PWD/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
# -----------
apd:
  stage: build 
  script:
    - GIT_SSH_COMMAND='ssh -i .ssh/id_rsa_user -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' pip install apd
    - eval "$(apd-login)"  # authenticate with Analysis Productions using this JWT
# -----------
install:
  cache:
    key:
      files :
        - pyproject.toml
    paths:
      - ~/.cache/pip
  stage: build
  script:
    - echo $PWD/.ssh
    - ls $PWD/.ssh
    - GIT_SSH_COMMAND='ssh -i .ssh/id_rsa_user -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' pip install -e .
# -----------
test_eos:
  stage: test
  script:
    root -l -q /eos/lhcb/wg/RD/RX_run3/Data/rx/hop/v3/mc_magup_13454001_bs_jpsix_ee_eq_jpsiinacc_Hlt2RD_BuToKpEE_MVA_cal_72a6fc3576.root
# -----------
