image: docker.io/acampove/rx_run3:v2
# -----------
default:
  tags:
    - cvmfs
# -----------
stages :
  - build
  - test
# -----------
build:
  cache:
    key:
      files :
        - pyproject.toml
    paths:
      - ~/.cache/pip
  stage: build
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - pip install -e .
# -----------
test_eos:
  stage: test
  script:
    - ls /eos/lhcb/wg/RD/RX_run3
# -----------
