image: docker.io/acampove/rx_run3:v1
# -----------
default:
  tags:
    - cvmfs
# -----------
stages :
  - build
# -----------
build:
  cache:
    key:
      files :
        - pyproject.toml
    paths:
      - ~/.cache/pip
  stage: build
  script:
    - pip install -e .
