[project]
name        = 'rx_plotter'
version     = '0.0.1'
readme      = 'README.md'
dependencies= [
'data-manipulation-utilities',
'mplhep',
'rx_selection',
'rx_data',
]

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
compare='rx_plotter_scripts.compare:main'
data_mc='rx_plotter_scripts.data_mc:main'
binned ='rx_plotter_scripts.binned:main'
overlay='rx_plotter_scripts.overlay:main'
cutflow='rx_plotter_scripts.cutflow:main'
plot_2d='rx_plotter_scripts.plot_2d:main'
mass_bias_correction='rx_plotter_scripts.mass_bias_correction:main'

[tool.setuptools.package-data]
rx_plots_data=['rk/mass/*.yaml']
