[project]
name        = 'rx_plotter'
version     = '0.0.1'
readme      = 'README.md'
dependencies= [
'data-manipulation-utilities',
'mplhep',
'rx_selection',
'rx_data',
]

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
overlay='rx_plotter_scripts.overlay:main'
plot_1d='rx_plotter_scripts.plot_1d:main'
plot_2d='rx_plotter_scripts.plot_2d:main'

[tool.setuptools.package-data]
rx_plots_data=['rk/mass/*.yaml']
