[project]
name         = 'rx_plotter'
version      = '0.0.1'
readme       = 'README.md'
dependencies = [
  'apd',
  'hist',
  'boost-histogram',
  'mplhep',
  'prefect==3.4.9', # Latest up to July 2025
  'matplotlib',
  'pandas',
  'numpy',
  'omegaconf',
  'data-manipulation-utilities @ git+ssh://git@gitlab.cern.ch:7999/rx_run3/dmu.git@master',
  'rx-selection @ git+ssh://git@gitlab.cern.ch:7999/rx_run3/rx_selection.git@master',
  'rx-data @ git+ssh://git@gitlab.cern.ch:7999/rx_run3/rx_data.git@master',
]

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
high_q2cut          ='rx_plotter_scripts.high_q2cut:main'
leakage             ='rx_plotter_scripts.leakage:main'
compare             ='rx_plotter_scripts.compare:main'
data_mc             ='rx_plotter_scripts.data_mc:main'
binned              ='rx_plotter_scripts.binned:main'
overlay             ='rx_plotter_scripts.overlay:main'
cutflow             ='rx_plotter_scripts.cutflow:main'
plot_2d             ='rx_plotter_scripts.plot_2d:main'
validate_nopid      ='rx_plotter_scripts.validate_nopid:main'
mass_bias_correction='rx_plotter_scripts.mass_bias_correction:main'
efficiency_vs_q2    ='rx_plotter_scripts.efficiency_vs_q2:main'

[tool.setuptools.package-data]
rx_plotter_data=['*/*.yaml']
